### ISSUE TITLE
Issue with BoS and VS

### ISSUE THREAD

**Issue by mason112** [stephaneuler/board-of-symbols#5]
Made the process as descriped in the readme file. Using VS as compiler. Get the following error, when running it.

![boserror](https://cloud.githubusercontent.com/assets/15131313/10496881/219b7696-72c3-11e5-850e-4837ea4fd9a7.JPG)

**Comment by stephaneuler** [comment]
Please test the installation:
- open command window, go to MS VS directory
- run vsvarsall.bat
- go to BoS directory
- type cl - you should see something like
  Microsoft (R) C/C++-Optimierungscompiler Version 17.00.61030 für x86
  Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

Syntax: cl [ Option... ] Dateiname... [ /link Linkeroption... ]
- run jserver from command window (java -jar jserver.jar), the environment settings are shown when compiling.
  If all fails: contact me at stephan.euler@mnd.thm.de

**Comment by mason112** [comment]
made it work, after I changed from VS 14 to 11
