### ISSUE TITLE
Meldung im Dialogfenster beim Schließen des Codeeditors

### ISSUE THREAD

**Issue by thomasbreitbach** [stephaneuler/board-of-symbols#6]
Wenn der Codeeditor geschlossen werden soll und bereits bestehender Code verändert wurde erscheint folgende Meldung:
"Code wurde geändert, trotzdem neu schließen".
![dialog](https://cloud.githubusercontent.com/assets/3606319/10689974/148b60ac-797f-11e5-8a28-80c17a5d5dcb.png)

Meiner Meinung nach ist hier das "neu" zu viel.

Gruß
Thomas

**Comment by stephaneuler** [comment]
danke für den Hinweis, ist korrigiert
